"""
Phase 49: Guide-to-Litematic converter.

Converts Emma's guide block format (from BuildDB) to .litematic files
via the litemapy library. Generates sweep waypoints for Emmatone movement
during Printer operation and scaffold blocks for elevated builds.

Dependency: pip install litemapy
"""

import logging
import math
import os
from pathlib import Path
from typing import Optional

log = logging.getLogger(__name__)

# Default schematics directory for PrismLauncher
_DEFAULT_SCHEMATICS_DIR = os.path.join(
    os.environ.get("APPDATA", ""),
    "PrismLauncher", "instances", "Emma", ".minecraft", "schematics",
)


def _ensure_namespace(block_type: str) -> str:
    """Ensure block type has minecraft: prefix."""
    if ":" not in block_type:
        return f"minecraft:{block_type}"
    return block_type


def _strip_ns(name: str) -> str:
    """Strip 'minecraft:' prefix if present."""
    return name.replace("minecraft:", "")


def guide_to_litematic(
    blocks: list[dict],
    name: str,
    output_dir: str | None = None,
    deferred_set: set[str] | None = None,
    exclude_deferred: bool = True,
) -> dict:
    """Convert a guide block list to a .litematic file.

    Args:
        blocks: List of guide block dicts with keys:
            block_type, offset_x, offset_y, offset_z, block_state
        name: Schematic name (used for filename: {name}.litematic)
        output_dir: Output directory. Defaults to PrismLauncher schematics dir.
        deferred_set: Set of deferred block names (stripped). If None, imports
            from BuildDB.DEFERRED_BLOCKS.
        exclude_deferred: If True, skip deferred blocks (structural pass).
            If False, include ALL blocks (finishing pass).

    Returns:
        {status, file, block_count, dimensions, origin_offset}
    """
    try:
        from litemapy import Schematic, Region, BlockState
    except ImportError:
        return {"status": "error", "reason": "litemapy not installed (pip install litemapy)"}

    if deferred_set is None:
        from gamer.build_db import BuildDB
        deferred_set = BuildDB.DEFERRED_BLOCKS

    # Filter blocks
    filtered = []
    for b in blocks:
        bt = _strip_ns(b["block_type"])
        if exclude_deferred and bt in deferred_set:
            continue
        filtered.append(b)

    if not filtered:
        return {"status": "ok", "block_count": 0, "message": "No blocks to export"}

    # Compute bounding box
    min_x = min(b["offset_x"] for b in filtered)
    min_y = min(b["offset_y"] for b in filtered)
    min_z = min(b["offset_z"] for b in filtered)
    max_x = max(b["offset_x"] for b in filtered)
    max_y = max(b["offset_y"] for b in filtered)
    max_z = max(b["offset_z"] for b in filtered)

    width = max_x - min_x + 1
    height = max_y - min_y + 1
    length = max_z - min_z + 1

    # Create schematic
    schem = Schematic(name=name, author="Emma", description="Generated by Emma AI")
    reg = Region(0, 0, 0, width, height, length)

    placed = 0
    for b in filtered:
        rx = b["offset_x"] - min_x
        ry = b["offset_y"] - min_y
        rz = b["offset_z"] - min_z
        bt = _ensure_namespace(b["block_type"])
        bs = b.get("block_state") or {}
        # Convert all state values to strings (litemapy 0.11 uses kwargs)
        props = {str(k): str(v) for k, v in bs.items()} if bs else {}
        try:
            reg[rx, ry, rz] = BlockState(bt, **props) if props else BlockState(bt)
            placed += 1
        except Exception as exc:
            log.warning("Failed to set block %s at (%d,%d,%d): %s", bt, rx, ry, rz, exc)

    schem.regions["Main"] = reg

    # Save
    out = output_dir or _DEFAULT_SCHEMATICS_DIR
    os.makedirs(out, exist_ok=True)
    filename = f"{name}.litematic"
    filepath = os.path.join(out, filename)
    schem.save(filepath)

    log.info("Saved %s (%d blocks, %dx%dx%d)", filepath, placed, width, height, length)

    return {
        "status": "ok",
        "file": filename,
        "filepath": filepath,
        "block_count": placed,
        "dimensions": {"width": width, "height": height, "length": length},
        "origin_offset": {"x": min_x, "y": min_y, "z": min_z},
    }


def convert_phase_plan(
    client,
    goal_id: int,
    output_dir: str | None = None,
    layer_height: int = 2,
    printer_range: float = 4.5,
) -> dict:
    """Full pipeline: goal blocks → per-phase .litematic files + sweep paths + BOMs.

    Args:
        client: EmmatoneClient with build_db
        goal_id: Build goal ID
        output_dir: Schematics output directory
        layer_height: Y-band height per phase
        printer_range: Printer placement reach

    Returns:
        {status, phases: [{file, sweep_waypoints, bom, ...}], finishing_phase}
    """
    from gamer.build_db import BuildDB
    from gamer.build_tools import _aggregate_bom_as_items

    goal = client.build_db.get_goal(goal_id)
    if not goal:
        return {"status": "error", "reason": f"Goal {goal_id} not found"}

    guide_id = goal.get("guide_id")
    if not guide_id:
        return {"status": "error", "reason": "Goal has no guide attached"}

    origin_x = goal.get("location_x", 0) or 0
    origin_y = goal.get("location_y", 0) or 0
    origin_z = goal.get("location_z", 0) or 0

    guide = client.build_db.get_guide(guide_id)
    build_name = guide["name"] if guide else f"guide_{guide_id}"
    safe_name = build_name.replace(" ", "_").lower()

    # Get all phases from BuildDB
    phases = client.build_db.split_into_phases(
        guide_id, layer_height=layer_height
    )

    phase_results = []
    for i, phase in enumerate(phases):
        y_min, y_max = phase["y_min"], phase["y_max"]

        # Get blocks for this Y-range (structural only for structural pass)
        band_blocks = client.build_db.get_blocks_for_y_range(guide_id, y_min, y_max)

        phase_name = f"{safe_name}_phase{i}"
        result = guide_to_litematic(
            band_blocks,
            phase_name,
            output_dir=output_dir,
            exclude_deferred=True,
        )

        if result.get("block_count", 0) == 0:
            continue

        # Origin offset: the .litematic's placement origin in world coordinates
        offset = result.get("origin_offset", {"x": 0, "y": 0, "z": 0})
        placement_origin = {
            "x": origin_x + offset["x"],
            "y": origin_y + offset["y"],
            "z": origin_z + offset["z"],
        }

        # Generate sweep waypoints (world coordinates)
        sweep = generate_sweep_path(
            band_blocks,
            origin_x, origin_y, origin_z,
            layer_height=layer_height,
            printer_range=printer_range,
        )

        # BOM for this phase
        bom = {}
        for b in band_blocks:
            bt = _strip_ns(b["block_type"])
            if bt not in BuildDB.DEFERRED_BLOCKS:
                bom[bt] = bom.get(bt, 0) + 1
        bom_items = _aggregate_bom_as_items(bom)

        phase_results.append({
            "index": i,
            "file": result["file"],
            "filepath": result.get("filepath"),
            "block_count": result["block_count"],
            "y_range": {"min": y_min, "max": y_max},
            "placement_origin": placement_origin,
            "sweep_waypoints": sweep,
            "bom": bom_items,
            "dimensions": result.get("dimensions"),
        })

    # Finishing phase (deferred blocks only)
    classified = client.build_db.classify_guide_blocks(guide_id)
    finishing = None
    if classified["deferred"]:
        finishing_name = f"{safe_name}_finishing"
        finishing_result = guide_to_litematic(
            classified["deferred"],
            finishing_name,
            output_dir=output_dir,
            exclude_deferred=False,
        )
        if finishing_result.get("block_count", 0) > 0:
            offset = finishing_result.get("origin_offset", {"x": 0, "y": 0, "z": 0})
            finishing_sweep = generate_sweep_path(
                classified["deferred"],
                origin_x, origin_y, origin_z,
                printer_range=printer_range,
            )
            finishing_bom = {}
            for b in classified["deferred"]:
                bt = _strip_ns(b["block_type"])
                finishing_bom[bt] = finishing_bom.get(bt, 0) + 1
            finishing = {
                "file": finishing_result["file"],
                "filepath": finishing_result.get("filepath"),
                "block_count": finishing_result["block_count"],
                "placement_origin": {
                    "x": origin_x + offset["x"],
                    "y": origin_y + offset["y"],
                    "z": origin_z + offset["z"],
                },
                "sweep_waypoints": finishing_sweep,
                "bom": _aggregate_bom_as_items(finishing_bom),
            }

    return {
        "status": "ok",
        "build_name": build_name,
        "phases": phase_results,
        "finishing_phase": finishing,
        "total_phases": len(phase_results) + (1 if finishing else 0),
    }


def generate_sweep_path(
    blocks: list[dict],
    origin_x: int = 0,
    origin_y: int = 0,
    origin_z: int = 0,
    layer_height: int = 2,
    printer_range: float = 4.5,
) -> list[dict]:
    """Generate back-and-forth sweep waypoints that bring every block within reach.

    Produces world-coordinate waypoints for Emmatone's goto() command.
    The sweep pattern is a lawn-mower path at each Y level.

    Args:
        blocks: Guide blocks with offset_x/y/z
        origin_x/y/z: World origin of the build
        layer_height: Y-band for grouping layers
        printer_range: Max placement distance (default 4.5 blocks)

    Returns:
        List of waypoint dicts: [{x, y, z}, ...]
    """
    if not blocks:
        return []

    # Spacing between sweep rows — must be < 2 * printer_range for full coverage
    spacing = max(1, int(printer_range * 1.5))

    min_x = min(b["offset_x"] for b in blocks)
    max_x = max(b["offset_x"] for b in blocks)
    min_y = min(b["offset_y"] for b in blocks)
    max_y = max(b["offset_y"] for b in blocks)
    min_z = min(b["offset_z"] for b in blocks)
    max_z = max(b["offset_z"] for b in blocks)

    waypoints = []
    forward = True  # toggle for back-and-forth

    # Walk at Y levels that cover the build (stand on same level as blocks)
    for y in range(min_y, max_y + 1, layer_height):
        # Walk Y is 1 above block level (standing on it)
        walk_y = origin_y + y

        # Sweep along X, stepping through Z
        for z_off in range(min_z - 1, max_z + 2, spacing):
            if forward:
                x_range = range(min_x - 1, max_x + 2, spacing)
            else:
                x_range = range(max_x + 1, min_x - 2, -spacing)

            for x_off in x_range:
                waypoints.append({
                    "x": origin_x + x_off,
                    "y": walk_y,
                    "z": origin_z + z_off,
                })
            forward = not forward

    # Deduplicate consecutive identical waypoints
    if waypoints:
        deduped = [waypoints[0]]
        for wp in waypoints[1:]:
            if wp != deduped[-1]:
                deduped.append(wp)
        waypoints = deduped

    return waypoints


def generate_scaffold_blocks(
    blocks: list[dict],
    pillar_spacing: int = 4,
    min_height: int = 4,
) -> list[dict]:
    """Generate dirt scaffold pillars + walkway platforms around the build perimeter.

    Scaffold blocks allow safe access to elevated sections (roofs) by providing
    flat walkways at each Y level. Used as a separate build phase before roof.

    Args:
        blocks: Guide blocks (the actual build, not including scaffold)
        pillar_spacing: Distance between scaffold pillars along edges
        min_height: Minimum build height to trigger scaffolding

    Returns:
        List of scaffold block dicts (same format as guide blocks, block_type=dirt)
    """
    if not blocks:
        return []

    min_x = min(b["offset_x"] for b in blocks)
    max_x = max(b["offset_x"] for b in blocks)
    min_y = min(b["offset_y"] for b in blocks)
    max_y = max(b["offset_y"] for b in blocks)
    min_z = min(b["offset_z"] for b in blocks)
    max_z = max(b["offset_z"] for b in blocks)

    height = max_y - min_y + 1
    if height < min_height:
        return []

    # Build set of occupied positions (don't place scaffold where build blocks go)
    occupied = {(b["offset_x"], b["offset_y"], b["offset_z"]) for b in blocks}

    scaffold = []
    order = 0

    # Perimeter ring: 1 block outside the build footprint
    ring_min_x, ring_max_x = min_x - 2, max_x + 2
    ring_min_z, ring_max_z = min_z - 2, max_z + 2

    # Generate pillar positions along the perimeter
    pillar_positions = []

    # Corners
    for x in [ring_min_x, ring_max_x]:
        for z in [ring_min_z, ring_max_z]:
            pillar_positions.append((x, z))

    # Along edges at pillar_spacing intervals
    for x in range(ring_min_x, ring_max_x + 1, pillar_spacing):
        pillar_positions.append((x, ring_min_z))
        pillar_positions.append((x, ring_max_z))
    for z in range(ring_min_z, ring_max_z + 1, pillar_spacing):
        pillar_positions.append((ring_min_x, z))
        pillar_positions.append((ring_max_x, z))

    # Deduplicate
    pillar_positions = list(set(pillar_positions))

    # Build pillars from ground to max_y
    for px, pz in pillar_positions:
        for y in range(min_y, max_y + 1):
            if (px, y, pz) not in occupied:
                scaffold.append({
                    "block_type": "minecraft:dirt",
                    "offset_x": px,
                    "offset_y": y,
                    "offset_z": pz,
                    "block_state": {},
                    "placement_order": order,
                    "is_scaffold": True,
                })
                order += 1

    # Walkway platforms at each layer_height interval (every 3 Y levels)
    walkway_interval = 3
    for y in range(min_y + walkway_interval, max_y + 1, walkway_interval):
        # Connect pillars along edges with walkway blocks
        for x in range(ring_min_x, ring_max_x + 1):
            for z in [ring_min_z, ring_max_z]:
                if (x, y, z) not in occupied:
                    scaffold.append({
                        "block_type": "minecraft:dirt",
                        "offset_x": x,
                        "offset_y": y,
                        "offset_z": z,
                        "block_state": {},
                        "placement_order": order,
                        "is_scaffold": True,
                    })
                    order += 1
        for z in range(ring_min_z, ring_max_z + 1):
            for x in [ring_min_x, ring_max_x]:
                if (x, y, z) not in occupied:
                    scaffold.append({
                        "block_type": "minecraft:dirt",
                        "offset_x": x,
                        "offset_y": y,
                        "offset_z": z,
                        "block_state": {},
                        "placement_order": order,
                        "is_scaffold": True,
                    })
                    order += 1

    # Deduplicate by position
    seen = set()
    deduped = []
    for s in scaffold:
        key = (s["offset_x"], s["offset_y"], s["offset_z"])
        if key not in seen:
            seen.add(key)
            deduped.append(s)

    log.info("Generated %d scaffold blocks for %dx%dx%d build",
             len(deduped), max_x - min_x + 1, height, max_z - min_z + 1)

    return deduped
