org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric properties
minecraft_version=26.1
loader_version=0.18.4
loom_version=1.15.5

# Mod Properties
mod_version=0.1.0
maven_group=com.emma.recipeextractor
archives_base_name=emma-recipe-extractor

# Dependencies
fabric_version=0.143.14+26.1
